import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion';
import { Img } from '../components/elements/Img';

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Nate Collins - Web Development</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/logo.png" />
      </Head>



      <div className='w-full flex justify-center mt-24'>
        <div className=' flex flex-col px-20 justify-start items-center '>
          <span className=' w-full text-5xl font-light tracking-[.3em] text-purplegray-2 mb-16'>Nathaniel Collins</span>
          <div className='w-full flex flex-row justify-between items-center'>

            {/* Profile */}
            <div className='p-4 bg-[#391c1d] rounded-md shadow-sm shadow-gray-1 w-80 h-80'>
              <Img src='/prof.png' className=' rounded-md shadow-sm shadow-gray-2 '/>
            </div>

            {/* Text */}
            <div className='flex flex-col font-semibold mx-16  text-purplegray-1' >
              <div>Hello!</div>
              <div className='max-w-[280px] tracking-wider '>I'm Nate, software engineer, web developer, app builder and game maker. I take enourmous joy in finding elegant solutions to complicated conundroms. </div>
              <div></div>

            </div>

          </div>
        </div>

      </div>
    </div>
  )
}
